// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Dsproject_Server
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Survived")]
            public float Survived { get; set; }

            [ColumnName(@"Sex")]
            public float Sex { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"SibSp")]
            public float SibSp { get; set; }

            [ColumnName(@"Parch")]
            public float Parch { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [ColumnName(@"Pclass_1")]
            public float Pclass_1 { get; set; }

            [ColumnName(@"Pclass_2")]
            public float Pclass_2 { get; set; }

            [ColumnName(@"Pclass_3")]
            public float Pclass_3 { get; set; }

            [ColumnName(@"Embarked_C")]
            public float Embarked_C { get; set; }

            [ColumnName(@"Embarked_Q")]
            public float Embarked_Q { get; set; }

            [ColumnName(@"Embarked_S")]
            public float Embarked_S { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Survived")]
            public uint Survived { get; set; }

            [ColumnName(@"Sex")]
            public float Sex { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"SibSp")]
            public float SibSp { get; set; }

            [ColumnName(@"Parch")]
            public float Parch { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [ColumnName(@"Pclass_1")]
            public float Pclass_1 { get; set; }

            [ColumnName(@"Pclass_2")]
            public float Pclass_2 { get; set; }

            [ColumnName(@"Pclass_3")]
            public float Pclass_3 { get; set; }

            [ColumnName(@"Embarked_C")]
            public float Embarked_C { get; set; }

            [ColumnName(@"Embarked_Q")]
            public float Embarked_Q { get; set; }

            [ColumnName(@"Embarked_S")]
            public float Embarked_S { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
